### PR TITLE
i1096 - fix db restore without redeploy on science

### PR DESCRIPTION
**Pull request by richfitz**
We will *eventually* get this running as a cron job.

The changes in versions.py make things a little less sensitive to working directories.  The other changes are mostly about getting the notifier working and creating test users if required

### CODE REVIEW

**Comment by richfitz** [comment]
NOTE: to be really cron-able this needs to get authenticated with the vault without prompting

**Comment by richfitz** [comment]
https://vimc.slack.com/archives/C835184N6/p1511886036000194

**Comment by MartinEden** [comment]
What is the Slack message about? That just takes me to somewhere in #montagu-deploy...

**Comment by richfitz** [comment]
That's an example message added in this PR (here: https://github.com/vimc/montagu/pull/54/files#diff-b52c3278761b1b251e47dccca3ca2b78R23)

**Comment by MartinEden** [comment]
I think Slack was failing to take me to right message :(

**Comment by richfitz** [comment]
Yeah, that's correct.  There's still an additional unresolved issue (that probably should be elsewhere) about how to get this running via cron.

Oh, one more thing:

4. sets up the test_user if the settings had required one

**Comment by MartinEden** [comment]
That was the second thing I said :P

**Comment by richfitz** [comment]
Ah sorry

**Pull request merged**
