### PR TITLE
Update VIMC architecture XML and PNG

### PR DESCRIPTION
**Pull request by weshinsley**
Updates to VIMC architecture diagram:
Storage server added, and IPs (both 12.0.0.x - 40Gb, and the college enterprise IPs) labelled.

### CODE REVIEW

**Comment by richfitz** [comment]
Other things to fix:

* The scheduler can come out because we don't have one (or immediate plans to get one)
* The orderly runner container is now a solid circle - there should be a link between it and the orderly api  on port 8123.  The orderly api is usually called the "reporting api"

**Comment by weshinsley** [comment]
OK - take a look  @MartinEden @richfitz and check I've got those right.

**Comment by MartinEden** [comment]
Thanks so much Wes - this has ended up as a bigger job than I expected!

**Comment by MartinEden** [comment]
As agreed with Rich, I'm going to merge the work done so far, as it's worth having, and I'll raise a ticket for the remaining changes Rich suggested.

**Comment by richfitz** [comment]
Please assign me that ticket and I'll pick it up at the same time I (eventually) do the other annex doc work

**Comment by MartinEden** [comment]
Actually, I'm not sure - @weshinsley, have you already made all the suggested changes?

**Comment by weshinsley** [comment]
Don't think I had anything outstanding.

**Comment by weshinsley** [comment]
(Except the animated version, with soundtrack)

**Pull request merged**
