### PR TITLE
Give user CLI real username and password if needed

### PR DESCRIPTION
**Pull request by MartinEden**
https://vimc.myjetbrains.com/youtrack/issue/VIMC-478

### CODE REVIEW

**Comment by richfitz** [comment]
I don't think this is fixed:

```
rich@wpia-dide136 ~/Documents/Projects/epi/vimc/montagu $ ./src/cli.py add
(Connecting to database as db user 'api')
Fill in the following fields to add a new user to the database:
Full name: Rich FitzJohn
Username [rich.fitzjohn]: rich
Email address [rich.fitzjohn@imperial.ac.uk]: r.fitzjohn@imperial.ac.uk
Password: 
[main] INFO org.jooq.Constants - 
                                      
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@  @@        @@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@        @@@@@@@@@@
@@@@@@@@@@@@@@@@  @@  @@    @@@@@@@@@@
@@@@@@@@@@  @@@@  @@  @@    @@@@@@@@@@
@@@@@@@@@@        @@        @@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@        @@        @@@@@@@@@@
@@@@@@@@@@    @@  @@  @@@@  @@@@@@@@@@
@@@@@@@@@@    @@  @@  @@@@  @@@@@@@@@@
@@@@@@@@@@        @@  @  @  @@@@@@@@@@
@@@@@@@@@@        @@        @@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@  @@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  Thank you for using jOOQ 3.9.1
                                      
Saved user 'rich.fitzjohn' to the database
rich@wpia-dide136 ~/Documents/Projects/epi/vimc/montagu $ git rev-parse HEAD
81518a45ddba9ba801738fb340cee6db6d64724f
```

(investigating further but keeping this here in case I lose the relevant snippet above).

**Comment by richfitz** [comment]
I cannot login with the email I provided, but if I log in with the default one (rich.fitzjohn@imperial.ac.uk) to the reporting portal I get the error in the web interface:

```
Your account has been deactivated. Please contact t.garske@imperial.ac.uk for help.
```

**Comment by littledice** [comment]
Looks like the add user functionality doesn't automatically add the permissions you need to log in.  Try running
`./src/cli.py addRole rich.fitzjohn user`
and
`./src/cli.py addRole rich.fitzjohn reports-reviewer`

**Comment by richfitz** [comment]
Sorry, I should have added that I did to that (Martin had sent me the bits to add over slack last week)

**Comment by littledice** [comment]
Can you see those roles saved against your user in the db?

**Comment by richfitz** [comment]
I had run 

```
./src/cli.py addRole rich.fitzjohn reports.viewer
```

which did not add anything, but I can now see those roles:

```
montagu=# SELECT * FROM user_role JOIN role ON role.id = user_role.role WHERE username = 'rich.fitzjohn';
   username    | role | scope_id | id |       name       | scope_prefix |                            description                             
---------------+------+----------+----+------------------+--------------+--------------------------------------------------------------------
 rich.fitzjohn |    1 |          |  1 | user             |              | Log in
 rich.fitzjohn |    7 |          |  7 | reports-reviewer |              | Choose which reports to publish (and can view unpublished reports)
(2 rows)
```

**Comment by richfitz** [comment]
After updating api to 341b55c

```
rich@wpia-dide136 ~/Documents/Projects/epi/vimc/montagu $ ./src/cli.py add 
(Connecting to database as db user 'api')
Unable to find image 'docker.montagu.dide.ic.ac.uk:5000/montagu-cli:341b55c' locally
341b55c: Pulling from montagu-cli
Digest: sha256:68db62ac029f106114a5737b9acef668dc32816377e7ca9fdb37e4a76fce9bc8
Status: Downloaded newer image for docker.montagu.dide.ic.ac.uk:5000/montagu-cli:341b55c
Fill in the following fields to add a new user to the database:
Full name: Rich FitzJohn
Username [rich.fitzjohn]: rich
Email address [rich@imperial.ac.uk]: r.fitzjohn@imperial.ac.uk
Password: 
[main] INFO org.jooq.Constants - 
                                      
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@  @@        @@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@        @@@@@@@@@@
@@@@@@@@@@@@@@@@  @@  @@    @@@@@@@@@@
@@@@@@@@@@  @@@@  @@  @@    @@@@@@@@@@
@@@@@@@@@@        @@        @@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@        @@        @@@@@@@@@@
@@@@@@@@@@    @@  @@  @@@@  @@@@@@@@@@
@@@@@@@@@@    @@  @@  @@@@  @@@@@@@@@@
@@@@@@@@@@        @@  @  @  @@@@@@@@@@
@@@@@@@@@@        @@        @@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@  @@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  Thank you for using jOOQ 3.9.1
                                      
Saved user 'rich' to the database
```

**Comment by richfitz** [comment]
@MartinEden - I've updated the api version on this branch and confirmed things working as expected

**Pull request merged**
